hide_download: true
hide_download_original: null
leftnav:
- identifier: c132de81-5af8-8035-be36-71acefbb5e19
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: d4413815-e386-5810-5cc3-aa61deef91c6
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 245ad9ac-38c1-c126-924f-3ba1538959b0
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 3b84b8cc-070a-6f69-e001-a514d56bdf93
  name: Lecture Slides
  pageRef: /pages/lecture-slides
  weight: 40
- identifier: b8e6ad3a-6045-257c-c3f6-df01da54c3f0
  name: Assignments
  pageRef: /pages/assignments
  weight: 50
